import assert from "node:assert/strict";
import test from "node:test";
import fs from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { createJiti } from "jiti";
const jiti = createJiti(import.meta.url, { tsconfigPaths: true });
const store = await jiti.import("./wallpaper-store.ts");
const { parseWallpaperPreferences } = await jiti.import("./wallpapers.ts");
const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=", "base64");
test("wallpaper preferences are bounded and reject invalid identifiers", () => {
  assert.equal(parseWallpaperPreferences("broken").id, null);
  assert.equal(parseWallpaperPreferences('{"id":"../../secret","brightness":500,"glass":"weird"}').brightness, 100);
  assert.equal(parseWallpaperPreferences('{"id":"../../secret"}').id, null);
  assert.equal(parseWallpaperPreferences('{"glass":"clear"}').glass, "clear");
  assert.equal(parseWallpaperPreferences(null).glassOpacity, 35);
  assert.equal(parseWallpaperPreferences(null).adaptiveText, true);
  assert.equal(parseWallpaperPreferences(null).textMode, "material");
  assert.equal(parseWallpaperPreferences('{"textMode":"auto"}').textMode, "auto");
  assert.equal(parseWallpaperPreferences('{"textMode":"fixed","textColor":"#ABCDEF"}').textColor, "#abcdef");
  assert.equal(parseWallpaperPreferences('{"textMode":"fixed"}').textMode, "fixed");
  assert.equal(parseWallpaperPreferences('{"textMode":"unknown","textColor":"red"}').textMode, "material");
  assert.equal(parseWallpaperPreferences('{"textColor":"url(secret)"}').textColor, "#e4e6ed");
  assert.equal(parseWallpaperPreferences('{"adaptiveText":false}').adaptiveText, false);
  assert.equal(parseWallpaperPreferences('{"adaptiveText":"false"}').adaptiveText, true);
  assert.equal(parseWallpaperPreferences(null).adaptivePalette, false);
  assert.equal(parseWallpaperPreferences('{"adaptivePalette":true}').adaptivePalette, true);
  assert.equal(parseWallpaperPreferences('{"adaptivePalette":"true"}').adaptivePalette, false);
  assert.equal(parseWallpaperPreferences('{"brightness":75}').glassOpacity, 35);
  assert.equal(parseWallpaperPreferences('{"glassOpacity":18}').glassOpacity, 18);
  assert.equal(parseWallpaperPreferences('{"glassOpacity":-5}').glassOpacity, 0);
  assert.equal(parseWallpaperPreferences('{"glassOpacity":150}').glassOpacity, 100);
  assert.equal(parseWallpaperPreferences('{"glassOpacity":"20"}').glassOpacity, 35);
  assert.equal(parseWallpaperPreferences('{"kind":"scene"}').kind, "scene");
});
test("video ranges handle open, suffix, invalid and multiple ranges", () => {
  assert.equal(store.mediaRange(null, 100), null);
  assert.deepEqual(store.mediaRange("bytes=10-19", 100), { start: 10, end: 19 });
  assert.deepEqual(store.mediaRange("bytes=10-", 100), { start: 10, end: 99 });
  assert.deepEqual(store.mediaRange("bytes=-20", 100), { start: 80, end: 99 });
  assert.deepEqual(store.mediaRange("bytes=90-200", 100), { start: 90, end: 99 });
  for (const r of ["bytes=100-", "bytes=20-10", "bytes=-0", "bytes=-", "bytes=1-2,3-4", "junk"]) assert.throws(() => store.mediaRange(r, 100));
});
test("Steam library VDF decodes escaped paths", () => {
  assert.deepEqual(store.steamLibraryPaths('"libraryfolders" { "0" { "path" "D:\\\\SteamLibrary" } }'), ["D:\\SteamLibrary"]);
});
test("library imports stream, reject spoofed content, keep WE scenes distinct and never delete originals", async t => {
  const root = await fs.mkdtemp(path.join(tmpdir(), "omp-wallpaper-test-"));
  const old = process.env.PI_CODING_AGENT_DIR;
  const oldRoots = process.env.OMP_WEB_WALLPAPER_DIRS;
  process.env.PI_CODING_AGENT_DIR = path.join(root, "agent");
  process.env.OMP_WEB_WALLPAPER_DIRS = "";
  store.invalidateWallpapers();
  t.after(async () => {
    if (old === undefined) delete process.env.PI_CODING_AGENT_DIR; else process.env.PI_CODING_AGENT_DIR = old;
    if (oldRoots === undefined) delete process.env.OMP_WEB_WALLPAPER_DIRS; else process.env.OMP_WEB_WALLPAPER_DIRS = oldRoots;
    store.invalidateWallpapers();
    const resolved = await fs.realpath(root);
    assert.ok(resolved.startsWith(await fs.realpath(tmpdir())) && path.basename(resolved).startsWith("omp-wallpaper-test-"));
    await fs.rm(resolved, { recursive: true, force: true });
  });
  const imported = await store.importWallpaper(new Request("http://localhost/upload", { method: "POST", body: png }), "test.png");
  let list = await store.listWallpapers(true);
  assert.equal(list.wallpapers.length, 1);
  const media = await store.resolveWallpaperMedia(imported.id, false);
  assert.deepEqual(await media.handle.readFile(), png);
  await media.handle.close();
  await assert.rejects(store.importWallpaper(new Request("http://localhost/upload", { method: "POST", body: "<html>bad</html>" }), "fake.png"));
  await assert.rejects(store.importWallpaper(new Request("http://localhost/upload", { method: "POST", body: png, headers: { "content-length": String(store.MAX_WALLPAPER_BYTES + 1) } }), "large.png"));
  await assert.rejects(store.importWallpaper(new Request("http://localhost/upload", { method: "POST", body: png }), ".hidden.png"));
  const originals = path.join(root, "originals");
  const scene = path.join(originals, "scene");
  await fs.mkdir(scene, { recursive: true });
  await fs.writeFile(path.join(scene, "preview.png"), png);
  await fs.writeFile(path.join(scene, "project.json"), JSON.stringify({ type: "scene", file: "scene.json", preview: "preview.png", title: "Real scene" }));
  await fs.writeFile(path.join(originals, "image.png"), png);
  await store.addWallpaperRoot(originals);
  list = await store.listWallpapers(true);
  assert.equal(list.wallpapers.length, 3);
  const item = list.wallpapers.find(w => w.kind === "scene");
  assert.ok(item.preview);
  await assert.rejects(store.resolveWallpaperMedia(item.id, false));
  await assert.rejects(store.resolveSceneProject("../private"));
  await assert.rejects(store.resolveSceneProject(item.id));
  await fs.writeFile(path.join(scene, "scene.pkg"), "scene fixture");
  const sceneProject = await store.resolveSceneProject(item.id);
  assert.equal(sceneProject.project, path.join(scene, "project.json"));
  await assert.rejects(store.resolveSceneProject(imported.id));
  const preview = await store.resolveWallpaperMedia(item.id, true);
  await preview.handle.close();
  await assert.rejects(store.deleteWallpaper(item.id));
  await assert.rejects(store.safeWallpaperFile(scene, "../image.png"));
  await assert.rejects(store.safeWallpaperFile(scene, "/etc/passwd"));
  await assert.rejects(store.safeWallpaperFile(scene, "..\\image.png"));
  const link = path.join(scene, "escape");
  await fs.symlink(originals, link, "junction");
  await assert.rejects(store.safeWallpaperFile(scene, "escape/image.png"));
  await fs.rmdir(link);
  await store.deleteWallpaper(imported.id);
  assert.equal((await store.listWallpapers(true)).wallpapers.length, 2);
  assert.deepEqual(await fs.readFile(path.join(originals, "image.png")), png);
});
